
import { jsPDF } from "jspdf";
import { AssessmentResult, FinancialData, User, DailySalesEntry } from "../types";

export const generatePDFReport = (user: User, data: FinancialData, assessment: AssessmentResult) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let currentY = 0;

  const addHeader = (text: string, y: number) => {
    doc.setFillColor(241, 245, 249);
    doc.rect(15, y, pageWidth - 30, 8, 'F');
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(text.toUpperCase(), 20, y + 6);
    return y + 15;
  };

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text("FINPULSE AI", 15, 25);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text("PROFESSIONAL SME FINANCIAL HEALTH CERTIFICATE", 15, 33);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(`REPORT ID: ${Date.now().toString().slice(-8).toUpperCase()}`, pageWidth - 15, 20, { align: "right" });
  doc.text(`ISSUED ON: ${new Date().toLocaleString()}`, pageWidth - 15, 25, { align: "right" });

  currentY = 60;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("BUSINESS PROFILE", 15, currentY);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Entity: ${user.businessName || 'N/A'}`, 15, currentY + 8);
  doc.text(`GSTIN: ${user.gstNumber || 'UNREGISTERED'}`, 15, currentY + 14);

  currentY += 30;
  currentY = addHeader("Core Financial Indices", currentY);
  
  const boxWidth = (pageWidth - 40) / 3;
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(15, currentY, boxWidth, 25, 3, 3, 'FD');
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text("BUSINESS TRUST", 20, currentY + 8);
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.text(`${assessment.creditScore}`, 20, currentY + 18);

  currentY += 40;
  currentY = addHeader("Strategic Analysis & Insights", currentY);
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  
  assessment.insights.forEach((insight) => {
    const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - 40);
    doc.text(lines, 20, currentY);
    currentY += (lines.length * 5) + 2;
  });

  doc.save(`${user.businessName?.replace(/\s+/g, '_')}_Growth_Report.pdf`);
};

export const generateMonthlyRevenueReport = (user: User, month: string, year: string, entries: DailySalesEntry[]) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("MONTHLY REVENUE REPORT", 15, 22);
  doc.setFontSize(10);
  doc.text(`${month.toUpperCase()} ${year}`, 15, 30);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.text("BUSINESS DETAILS", 15, 55);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Shop Name: ${user.businessName || 'N/A'}`, 15, 63);
  doc.text(`Owner: ${user.name}`, 15, 69);

  const total = entries.reduce((sum, e) => sum + e.amount, 0);
  const avg = entries.length > 0 ? total / entries.length : 0;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(pageWidth - 85, 50, 70, 30, 3, 3, 'F');
  doc.setTextColor(37, 99, 235);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("TOTAL SALES THIS MONTH", pageWidth - 80, 58);
  doc.setFontSize(16);
  doc.text(`INR ${total.toLocaleString('en-IN')}`, pageWidth - 80, 70);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text("DAILY SALES BREAKDOWN", 15, 95);
  doc.line(15, 97, pageWidth - 15, 97);

  let currentY = 105;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("DATE", 20, currentY);
  doc.text("AMOUNT (INR)", pageWidth - 40, currentY, { align: "right" });
  doc.setFont("helvetica", "normal");
  
  currentY += 8;
  entries.sort((a, b) => a.date.localeCompare(b.date)).forEach((entry, idx) => {
    if (currentY > 270) {
      doc.addPage();
      currentY = 20;
    }
    if (idx % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(15, currentY - 5, pageWidth - 30, 8, 'F');
    }
    doc.text(entry.date, 20, currentY);
    doc.text(entry.amount.toLocaleString('en-IN'), pageWidth - 40, currentY, { align: "right" });
    currentY += 8;
  });

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Report generated by FinPulse AI. All data is self-reported by the shop owner.", pageWidth / 2, 285, { align: "center" });

  doc.save(`${user.businessName || 'Shop'}_Revenue_${month}_${year}.pdf`);
};
